[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Simple Streamlit App"
requires-python = ">=3.11"

dependencies = [
    "streamlit>=1.47.0",
    "requests>=2.32.4",
]

[tool.poetry]
package-mode = false
